// vue/src/App.vue
<template>
  <div>
    <div>App vue!</div>
    <button @click="generateLow()">Generate Low</button>
    <button @click="generateMedium()">Generate Medium</button>
    <button @click="generateHigh()">Generate High</button>
    <button @click="updateOne()">update 100</button>
    <button @click="updateTwo()">update 1000</button>
    <button @click="clear()">Clear</button>
    <div v-for="message in messages" :key="message.id">
        <MessageComponent :message="message" />
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import MessageComponent from "./Message.vue";
import { Data, dataGenerator, LOW, MEDIUM, HIGH } from "../../common";

@Component({
  components: {
    MessageComponent
  }
})
export default class AppComponent extends Vue {
  public messages: Data[] = [];

  public generateLow(): void {
    this.messages = dataGenerator(LOW);
  }

  public generateMedium(): void {
    this.messages = dataGenerator(MEDIUM);
  }

  public generateHigh(): void {
    this.messages = dataGenerator(HIGH);
  }

  public updateOne(): void {
    this.messages = this.messages.map(m => {
      if (m.id < 100) {
        m.text += "Updated";
      }

      return m;
    });
  }

  public updateTwo(): void {
    this.messages = this.messages.map(m => {
      if (m.id < 1000) {
        m.text += "Updated";
      }

      return m;
    });
  }

  public clear(): void {
    this.messages = [];
  }
}
</script>

// react/src/App.tsx
import * as React from 'react';

import { Message } from './Message';

import { Data, dataGenerator, HIGH, MEDIUM, LOW } from '../../common';

export interface HelloProps { compiler: string; framework: string; }

// 'HelloProps' describes the shape of props.
// State is never set so we use the '{}' type.
export class Hello extends React.Component<HelloProps, { messages: Array<Data> }> {

    public constructor(props: HelloProps) {
        super(props);

        this.state = {
            messages: []
        }
    }

    public generateLow(): void {
        this.setState({ messages: dataGenerator(LOW) });
    }

    public generateMedium(): void {
        this.setState({ messages: dataGenerator(MEDIUM) });
    }

    public generateHigh(): void {
        this.setState({ messages: dataGenerator(HIGH) });
    }

    public updateOne(): void {
        this.setState({
            messages: this.state.messages.map(m => {
                if (m.id < 100) {
                    m.text += 'Updated';
                }

                return m;
            })
        });
    }

    public updateTwo(): void {
        this.setState({
            messages: this.state.messages.map(m => {
                if (m.id < 1000) {
                    m.text += 'Updated';
                }

                return m;
            })
        });
    }

    public clear(): void {
        this.setState({ messages: [] });
    }

    public render(): JSX.Element {
        return (
            <div>
                <button onClick={this.generateLow.bind(this)}>generateLow</button>
                <button onClick={this.generateMedium.bind(this)}>generateMedium</button>
                <button onClick={this.generateHigh.bind(this)}>generateHigh</button>
                <button onClick={this.updateOne.bind(this)}>update 100</button>
                <button onClick={this.updateTwo.bind(this)}>update 1000</button>
                <button onClick={this.clear.bind(this)}>clear</button>
                <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>
                {this.state.messages.map(m => (
                    <Message key={m.id} message={m} />
                ))}
            </div>
        );
    }
}
